package app.marlboroadvance.mpvex.repository.wyzie

object WyzieLanguages {
    val ALL = mapOf(
        "en" to "English",
        "es" to "Spanish",
        "fr" to "French",
        "de" to "German",
        "it" to "Italian",
        "pt" to "Portuguese",
        "ru" to "Russian",
        "zh" to "Chinese",
        "ja" to "Japanese",
        "ko" to "Korean",
        "ar" to "Arabic",
        "hi" to "Hindi",
        "bn" to "Bengali",
        "pa" to "Punjabi",
        "jv" to "Javanese",
        "vi" to "Vietnamese",
        "te" to "Telugu",
        "mr" to "Marathi",
        "ta" to "Tamil",
        "ur" to "Urdu",
        "tr" to "Turkish",
        "pl" to "Polish",
        "uk" to "Ukrainian",
        "nl" to "Dutch",
        "el" to "Greek",
        "hu" to "Hungarian",
        "sv" to "Swedish",
        "cs" to "Czech",
        "ro" to "Romanian",
        "da" to "Danish",
        "fi" to "Finnish",
        "no" to "Norwegian",
        "he" to "Hebrew",
        "id" to "Indonesian",
        "ms" to "Malay",
        "th" to "Thai",
        "fa" to "Persian",
        "sk" to "Slovak",
        "bg" to "Bulgarian",
        "hr" to "Croatian",
        "sr" to "Serbian",
        "sl" to "Slovenian",
        "et" to "Estonian",
        "lv" to "Latvian",
        "lt" to "Lithuanian",
        "af" to "Afrikaans",
        "sq" to "Albanian",
        "am" to "Amharic",
        "hy" to "Armenian",
        "az" to "Azerbaijani",
        "eu" to "Basque",
        "be" to "Belarusian",
        "bs" to "Bosnian",
        "ca" to "Catalan",
        "cy" to "Welsh",
        "eo" to "Esperanto",
        "ga" to "Irish",
        "gl" to "Galician",
        "ka" to "Georgian",
        "gu" to "Gujarati",
        "ht" to "Haitian Creole",
        "is" to "Icelandic",
        "kn" to "Kannada",
        "kk" to "Kazakh",
        "km" to "Khmer",
        "ky" to "Kyrgyz",
        "lo" to "Lao",
        "mk" to "Macedonian",
        "mg" to "Malagasy",
        "mt" to "Maltese",
        "mi" to "Maori",
        "mn" to "Mongolian",
        "ne" to "Nepali",
        "ps" to "Pashto",
        "si" to "Sinhala",
        "sw" to "Swahili",
        "tg" to "Tajik",
        "tt" to "Tatar",
        "uz" to "Uzbek",
        "yi" to "Yiddish",
        "yo" to "Yoruba",
        "zu" to "Zulu"
    ).toSortedMap(compareBy { it }) // Sort by language name? No, value is name.
    
    // Sort by name (value)
    val SORTED = ALL.toList().sortedBy { it.second }.toMap()
}
